# -*- coding: utf-8 -*-
"""Normalize UI strings ID -> EN across HTML and Alpine components."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TARGETS = sorted(ROOT.glob("*.html")) + [ROOT / "assets" / "js" / "alpine" / "components.js"]

PAIRS: list[tuple[str, str]] = [
    ("Kode, murid, metode, dan tanggal wajib diisi.", "Code, student, method, and date are required."),
    ("Pembayaran diterima", "Payment received"),
    ("SPP Januari telah dibayar untuk Andi Pratama.", "January tuition has been paid for Andi Pratama."),
    ("Kelas 10A — uang gedung menunggu konfirmasi.", "Class 10A — building fee awaiting confirmation."),
    ("Kelas 10A \u2014 uang gedung menunggu konfirmasi.", "Class 10A — building fee awaiting confirmation."),
    ("Kelas 10A \u2013 uang gedung menunggu konfirmasi.", "Class 10A — building fee awaiting confirmation."),
    ("Undangan rapat orang tua", "Parent-teacher meeting invitation"),
    ("Anda diundang ke rapat koordinasi kelas XI IPA 1.", "You are invited to a coordination meeting for class XI IPA 1."),
    ("5 murid belum hadir hari ini.", "5 students were absent today."),
    ("Kehadiran siswa laki-laki &amp; perempuan (demo)", "Male and female student attendance (demo)"),
    ("Kehadiran siswa laki-laki & perempuan (demo)", "Male and female student attendance (demo)"),
    ("Aktivitas minggu ini vs rata-rata (demo).", "This week vs average activity (demo)."),
    ("Menit aktivitas", "Activity (minutes)"),
    ("Rentang statistik", "Statistics range"),
    ("Ekspor data grafik", "Export chart data"),
    ("Jumlah Tagihan", "Total invoices"),
    ("Murid Aktif", "Active students"),
    ("Tenaga Pengajar", "Faculty"),
    ("vs bulan lalu", "vs last month"),
    ("Lihat semua", "View all"),
    ("Mode terang/gelap", "Light and dark mode"),
    ("Profil pengguna", "User profile"),
    ("Menu ringkasan", "Summary menu"),
    ("Navigasi halaman", "Pagination"),
    ("Halaman pertama", "First page"),
    ("Halaman sebelumnya", "Previous page"),
    ("Halaman berikutnya", "Next page"),
    ("Halaman terakhir", "Last page"),
    ("Pilih semua di halaman ini", "Select all on this page"),
    ("Lihat detail", "View details"),
    ("Lihat dashboard", "View dashboard"),
    ("Kelola murid", "Manage students"),
    ("Kelola tagihan", "Manage invoices"),
    ("Atur role", "Manage roles"),
    ("Export laporan", "Export reports"),
    ("Tambah payment", "Add payment"),
    ("Tambah absensi", "Add attendance"),
    ("Tambah permission", "Add permission"),
    ("Tambah setting", "Add setting"),
    ("Tambah user", "Add user"),
    ("Tambah role", "Add role"),
    ("Tambah kelas", "Add class"),
    ("Tambah murid", "Add student"),
    ("Tambah guru", "Add teacher"),
    ("Tambah tagihan", "Add invoice"),
    ("'Tambah payment'", "'Add payment'"),
    ('"Tambah payment"', '"Add payment"'),
    ("'Edit payment' : 'Tambah payment'", "'Edit payment' : 'Add payment'"),
    ("'Edit kelas' : 'Tambah kelas'", "'Edit class' : 'Add class'"),
    ("'Edit murid' : 'Tambah murid'", "'Edit student' : 'Add student'"),
    ("'Edit guru' : 'Tambah guru'", "'Edit teacher' : 'Add teacher'"),
    ("'Edit tagihan' : 'Tambah tagihan'", "'Edit invoice' : 'Add invoice'"),
    ("'Edit absensi' : 'Tambah absensi'", "'Edit attendance' : 'Add attendance'"),
    ("'Edit role' : 'Tambah role'", "'Edit role' : 'Add role'"),
    ("'Edit user' : 'Tambah user'", "'Edit user' : 'Add user'"),
    ("'Edit setting' : 'Tambah setting'", "'Edit setting' : 'Add setting'"),
    ("'Edit' : 'Tambah'", "'Edit' : 'Add'"),
    ("Nama kelas atau wali…", "Class or homeroom teacher…"),
    ("Nama, email, role…", "Name, email, role…"),
    ("Nama atau slug…", "Name or slug…"),
    ("Key atau nilai…", "Key or value…"),
    ("Nama permission atau key…", "Permission name or key…"),
    ("Cari murid, email, status…", "Search student, email, status…"),
    ("Cari murid, email, status\uFFFD", "Search student, email, status…"),
    ("Cari murid, email, status", "Search student, email, status"),
    ("Kode, murid, atau metode…", "Code, student, or method…"),
    ("Nama murid atau NIS…", "Student name or ID…"),
    ("Nama guru atau mapel…", "Teacher name or subject…"),
    ("Nama murid atau jenis…", "Student name or type…"),
    ("Nama murid atau kelas…", "Student name or class…"),
    ("Nama murid", "Student name"),
    ("Nama guru", "Teacher name"),
    ("Wali kelas", "Homeroom teacher"),
    ("Nama kelas", "Class name"),
    ("Jumlah siswa", "Students"),
    ("Orang tua", "Parent"),
    ("Jatuh tempo", "Due date"),
    ("Detail payment", "Payment details"),
    ("Detail tagihan", "Invoice details"),
    ("Detail kelas", "Class details"),
    ("Detail murid", "Student details"),
    ("Detail guru", "Teacher details"),
    ("Detail absensi", "Attendance details"),
    ("Detail permission", "Permission details"),
    ("Detail setting", "Setting details"),
    ("Murid:", "Student:"),
    ("Jumlah:", "Amount:"),
    ("Tanggal:", "Date:"),
    ("Metode:", "Method:"),
    ("Kode:", "Code:"),
    ("Jenis:", "Type:"),
    ("Nominal:", "Amount:"),
    ("Nama kelas dan wali kelas wajib diisi.", "Class name and homeroom teacher are required."),
    ("Nama dan NIS wajib diisi.", "Name and student ID are required."),
    ("Nama dan mapel wajib diisi.", "Name and subject are required."),
    ("Nama murid dan kelas wajib diisi.", "Student name and class are required."),
    ("Nama murid dan tanggal wajib diisi.", "Student name and date are required."),
    ("Nama murid dan jenis wajib diisi.", "Student name and type are required."),
    ("Notifikasi", "Notifications"),
    ("Tagihan baru", "New invoice"),
    ("2 menit lalu", "2 minutes ago"),
    ("1 jam lalu", "1 hour ago"),
    ("1 hari lalu", "1 day ago"),
    ("Hari ini", "Today"),
    ("Terima", "Accept"),
    ("Tolak", "Decline"),
    ("Pengaturan akun", "Account settings"),
    ("Keluar", "Log out"),
    ("Buka menu", "Open menu"),
    ('aria-label="Cari"', 'aria-label="Search"'),
    ("'Hapus kelas", "'Delete class"),
    ("'Hapus murid", "'Delete student"),
    ("'Hapus guru", "'Delete teacher"),
    ("'Hapus tagihan", "'Delete invoice"),
    ("'Hapus absensi", "'Delete attendance"),
    ("'Hapus role", "'Delete role"),
    ("'Hapus user", "'Delete user"),
    ("'Hapus setting", "'Delete setting"),
    ("'Hapus permission", "'Delete permission"),
    ("'Hapus payment", "'Delete payment"),
    ("Hapus kelas", "Delete class"),
    ("Hapus murid", "Delete student"),
    ("Hapus guru", "Delete teacher"),
    ("Hapus tagihan", "Delete invoice"),
    ("Hapus absensi", "Delete attendance"),
    ("Hapus permission", "Delete permission"),
    ("Hapus setting", "Delete setting"),
    ("Hapus user", "Delete user"),
    ("Hapus role", "Delete role"),
    ("Hapus payment", "Delete payment"),
    ("Hapus", "Delete"),
    ("Batal", "Cancel"),
    ("Simpan", "Save"),
    ("Tutup", "Close"),
    ("Lihat", "View"),
    ("Grup", "Group"),
    ("Pengguna", "Users"),
    ("Mapel", "Subject"),
    ("Kontak", "Contact"),
    ("Keterangan", "Notes"),
    ("Kehadiran", "Attendance"),
    ("Tanggal", "Date"),
    ("Jumlah (Rp)", "Amount (IDR)"),
    ("Jumlah", "Amount"),
    ("Metode", "Method"),
    ("Kode", "Code"),
    ("Jenis", "Type"),
    ("Nominal", "Amount"),
    ("Nilai", "Value"),
    ("Kategori", "Category"),
    ("NIS", "Student ID"),
    ("Murid", "Student"),
    ("Guru", "Teacher"),
    ("Kelas", "Class"),
    ("Tagihan", "Invoices"),
    ("Absensi", "Attendance"),
    ("Tunai", "Cash"),
    ("Berhasil", "Success"),
    ("Gagal", "Failed"),
    ("Lunas", "Paid"),
    ("Terlambat", "Overdue"),
    ("Belum lunas", "Unpaid"),
    ("Aktif", "Active"),
    ("Nonaktif", "Inactive"),
    ("Umum", "General"),
    ("Akademik", "Academic"),
    ("Keuangan", "Finance"),
    ("Laporan", "Reports"),
    ("Profil", "Profile"),
    ("normalizeText(row.status) === 'berhasil'", "normalizeText(row.status) === 'success'"),
    ("normalizeText(row.status) === 'gagal'", "normalizeText(row.status) === 'failed'"),
    ("normalizeText(row.status) === 'aktif'", "normalizeText(row.status) === 'active'"),
    ("normalizeText(row.status) === 'lunas'", "normalizeText(row.status) === 'paid'"),
    ("normalizeText(row.status) === 'terlambat'", "normalizeText(row.status) === 'overdue'"),
    ("normalizeText(row.kehadiran) === 'hadir'", "normalizeText(row.kehadiran) === 'present'"),
    ("normalizeText(row.kehadiran) === 'alpha'", "normalizeText(row.kehadiran) === 'absent'"),
    ("normalizeText(row.kehadiran) === 'izin'", "normalizeText(row.kehadiran) === 'excused'"),
    ("toLocaleString('id-ID')", "toLocaleString('en-US')"),
    ("toLocaleDateString('id-ID'", "toLocaleDateString('en-US'"),
    ("toLocaleString(\"id-ID\")", "toLocaleString(\"en-US\")"),
    ("toLocaleDateString(\"id-ID\"", "toLocaleDateString(\"en-US\""),
    ("toLocaleLowerCase(\"id\")", "toLocaleLowerCase(\"en\")"),
    ('localeCompare(bs, "id"', 'localeCompare(bs, "en"'),
    ("Statistik kehadiran", "Attendance overview"),
    ("Distribusi pembayaran", "Payment distribution"),
    ("Pembayaran terbaru", "Recent payments"),
    ("Ekspor", "Export"),
    ("Bulan", "Month"),
    ("Minggu", "Week"),
    ("Hari", "Day"),
    ("Minggu ini", "This week"),
    ("Rata-rata", "Average"),
    ("Siswa Laki-laki", "Male students"),
    ("Siswa Perempuan", "Female students"),
    ("Senin", "Monday"),
    ("Selasa", "Tuesday"),
    ("Rabu", "Wednesday"),
    ("Kamis", "Thursday"),
    ("Jumat", "Friday"),
    ("Sabtu", "Saturday"),
    ("Januari", "January"),
    ("Februari", "February"),
    ("Maret", "March"),
    ("April", "April"),
    ("Mei", "May"),
    ("Juni", "June"),
    ("Tidak ada data", "No data"),
    ("return `Halaman ${this.page} dari ${this.totalPages}`", "return `Page ${this.page} of ${this.totalPages}`"),
    ("`${base} · ${sel} dari ${this.rows.length} dipilih`", "`${base} · ${sel} of ${this.rows.length} selected`"),
    ("Langsung", "Direct"),
    ("Medsos", "Social"),
    ("Lainnya", "Other"),
]


def main() -> None:
    for path in TARGETS:
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        orig = text
        for a, b in PAIRS:
            text = text.replace(a, b)
        if text != orig:
            path.write_text(text, encoding="utf-8")
            print("updated", path.relative_to(ROOT))


if __name__ == "__main__":
    main()
